version: '3.9'

services:

  django:
    container_name: djangocontainer
    build: 
      context: ./docker_test
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./docker_test:/usr/src/app/
    ports:
      - 8000:8000
      